use unicorn instead of thin

diff --git a/lib/pkgr/data/debian/init.d.erb b/lib/pkgr/data/debian/init.d.erb
--- a/lib/pkgr/data/debian/init.d.erb
+++ b/lib/pkgr/data/debian/init.d.erb
@@ -11,145 +11,66 @@
 ### END INIT INFO
 #
 
-PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
-NAME="<%= name %>"
-DAEMON=/usr/bin/$NAME
-DESC=$NAME
+set -u
+set -e
 
-test -x $DAEMON || exit 0
+# Change these to match your app:
+NAME=<%= name %>
+APP_ROOT=/opt/local/$NAME
 
 LOGDIR=/var/log/$NAME
 PIDFILE=/var/run/$NAME.pid
-DODTIME=5                   # Time to wait for the server to die, in seconds
-                            # If this value is set too low you might not
-                            # let some servers to die gracefully and
-                            # 'restart' will not work
+
+SET_PATH="cd $APP_ROOT"
 
 # Include defaults if available
 if [ -f /etc/default/$NAME ] ; then
   . /etc/default/$NAME
 fi
 
-set -e
+CMD="$SET_PATH; bundle exec unicorn_rails -c config/unicorn.rb $DAEMON_OPTS"
 
+old_pid="$PIDFILE.oldbin"
 
-running_pid()
-{
-    # Check if a given process status name matches a given name
-    pid=$1
-    name=$2
-    [ -z "$pid" ] && return 1
-    [ ! -d /proc/$pid ] &&  return 1
-    cmd=`cat /proc/$pid/status | grep Name: | cut -f 2`
-    # Is this the expected child?
-    [ "$cmd" != "$name" ] &&  return 1
-    return 0
+cd $APP_ROOT || exit 1
+
+sig () {
+  test -s "$PIDFILE" && kill -$1 `cat $PIDFILE`
 }
 
-running()
-{
-  # Check if the process is running looking at /proc
-  # (works for all users)
-    # No pidfile, probably no daemon present
-    [ ! -f "$PIDFILE" ] && return 1
-    # Obtain the pid
-    pid=`cat $PIDFILE`
-    running_pid $pid $NAME || return 1
-    return 0
+oldsig () {
+  test -s $old_pid && kill -$1 `cat $old_pid`
 }
 
-force_stop() {
-# Forcefully kill the process
-    [ ! -f "$PIDFILE" ] && return
-    if running ; then
-        kill -15 $pid
-        # Is it really dead?
-        [ -n "$DODTIME" ] && sleep "$DODTIME"s
-        if running ; then
-            kill -9 $pid
-            [ -n "$DODTIME" ] && sleep "$DODTIME"s
-            if running ; then
-                echo "Cannot kill $NAME (pid=$pid)!"
-                exit 1
-            fi
-        fi
-    fi
-    rm -f $PIDFILE
-    return 0
-}
-
-case "$1" in
-  start)
-  echo -n "Starting $DESC: "
-  if running ; then
-    echo "already running."
-  else
-    $DAEMON $DAEMON_OPTS start
-    # Needed to let Thin handle stale pid file.
-    sleep 1
-    if running ; then
-        echo "OK."
-    else
-        echo "ERROR."
-    fi
-  fi
+case ${1-help} in
+start)
+  sig 0 && echo >&2 "Already running" && exit 0
+  sh -c "$CMD"
   ;;
-  stop)
-  echo -n "Stopping $DESC: "
-  $DAEMON $DAEMON_OPTS stop
-  echo "OK."
+stop)
+  sig QUIT && exit 0
+  echo >&2 "Not running"
   ;;
-  force-stop)
-  echo -n "Forcefully stopping $DESC: "
-    force_stop
-    if ! running ; then
-        echo "OK."
-    else
-        echo "ERROR."
-    fi
+force-stop)
+  sig TERM && exit 0
+  echo >&2 "Not running"
   ;;
-  #reload)
-  #
-  # If the daemon can reload its config files on the fly
-  # for example by sending it SIGHUP, do it here.
-  #
-  # If the daemon responds to changes in its config file
-  # directly anyway, make this a do-nothing entry.
-  #
-  # echo "Reloading $DESC configuration files."
-  # start-stop-daemon --stop --signal 1 --quiet --pidfile \
-  # /var/run/$NAME.pid --exec $DAEMON
-  #;;
-  force-reload)
-  #
-  # If the "reload" option is implemented, move the "force-reload"
-  # option to the "reload" entry above. If not, "force-reload" is
-  # just the same as "restart" except that it does nothing if the
-  #   daemon isn't already running.
-  # check wether $DAEMON is running. If so, restart
-    if running ;  then
-      $0 restart
-    fi
+restart|reload)
+  sig HUP && echo reloaded OK && exit 0
+  echo >&2 "Couldn't reload, starting '$CMD' instead"
+  sh -c "$CMD"
   ;;
-  restart)
-    echo "Restarting $DESC..."
-    $0 stop && $0 start
+upgrade)
+  sig USR2 && exit 0
+  echo >&2 "Couldn't upgrade, starting '$CMD' instead"
+  sh -c "$CMD"
   ;;
-  status)
-    echo -n "$NAME is "
-    if running ;  then
-      echo "running."
-    else
-      echo "not running."
-      exit 1
-    fi
-    ;;
-  *)
-  N=/etc/init.d/$NAME
-  # echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
-  echo "Usage: $N {start|stop|restart|force-reload|status|force-stop}" >&2
+rotate)
+  sig USR1 && echo rotated logs OK && exit 0
+  echo >&2 "Couldn't rotate logs" && exit 1
+  ;;
+*)
+  echo >&2 "Usage: $0 <start|stop|restart|upgrade|rotate|force-stop>"
   exit 1
   ;;
 esac
-
-exit 0
